"""NIST Cybersecurity Framework 2.0 seed data."""

NIST_CSF_FAMILIES = [
    {
        "code": "GV",
        "name": "Govern",
        "description": "The organization's cybersecurity risk management strategy, expectations, and policy are established, communicated, and monitored.",
        "framework": "NIST_CSF",
        "version": "2.0",
        "is_active": True,
        "sort_order": 1,
    },
    {
        "code": "ID",
        "name": "Identify",
        "description": "The organization's current cybersecurity risks are understood.",
        "framework": "NIST_CSF",
        "version": "2.0",
        "is_active": True,
        "sort_order": 2,
    },
    {
        "code": "PR",
        "name": "Protect",
        "description": "Safeguards to manage the organization's cybersecurity risks are used.",
        "framework": "NIST_CSF",
        "version": "2.0",
        "is_active": True,
        "sort_order": 3,
    },
    {
        "code": "DE",
        "name": "Detect",
        "description": "Possible cybersecurity attacks and compromises are found and analyzed.",
        "framework": "NIST_CSF",
        "version": "2.0",
        "is_active": True,
        "sort_order": 4,
    },
    {
        "code": "RS",
        "name": "Respond",
        "description": "Actions regarding a detected cybersecurity incident are taken.",
        "framework": "NIST_CSF",
        "version": "2.0",
        "is_active": True,
        "sort_order": 5,
    },
    {
        "code": "RC",
        "name": "Recover",
        "description": "Assets and operations affected by a cybersecurity incident are restored.",
        "framework": "NIST_CSF",
        "version": "2.0",
        "is_active": True,
        "sort_order": 6,
    },
]

NIST_CSF_CONTROLS = [
    {
        "family_code": "GV",
        "code": "GV.OC-01",
        "name": "Organizational Context",
        "description": "The organizational mission, stakeholder expectations, and legal, regulatory, and contractual requirements are understood and inform cybersecurity roles, responsibilities, and risk management decisions.",
        "guidance": "Organizations should identify their mission and stakeholder expectations to inform cybersecurity risk management decisions.",
        "version": "2.0",
        "is_active": True,
        "priority": "high",
        "sort_order": 1,
    },
    {
        "family_code": "GV",
        "code": "GV.RM-01",
        "name": "Risk Management Strategy",
        "description": "Risk management strategy is established, communicated, and maintained.",
        "guidance": "A risk management strategy provides a structured approach to managing cybersecurity risks across the organization.",
        "version": "2.0",
        "is_active": True,
        "priority": "high",
        "sort_order": 2,
    },
    {
        "family_code": "GV",
        "code": "GV.RR-01",
        "name": "Roles and Responsibilities",
        "description": "Organizational cybersecurity roles and responsibilities are established and communicated.",
        "guidance": "Clear definition of roles and responsibilities ensures accountability for cybersecurity risk management.",
        "version": "2.0",
        "is_active": True,
        "priority": "high",
        "sort_order": 3,
    },
    {
        "family_code": "ID",
        "code": "ID.AM-01",
        "name": "Asset Management - Devices",
        "description": "Physical devices and systems within the organization are inventoried.",
        "guidance": "Maintain an inventory of all physical devices to understand the organization's attack surface.",
        "version": "2.0",
        "is_active": True,
        "priority": "high",
        "sort_order": 1,
    },
    {
        "family_code": "ID",
        "code": "ID.AM-02",
        "name": "Asset Management - Software",
        "description": "Software platforms and applications within the organization are inventoried.",
        "guidance": "Maintain an inventory of all software to identify potential vulnerabilities and manage licenses.",
        "version": "2.0",
        "is_active": True,
        "priority": "high",
        "sort_order": 2,
    },
    {
        "family_code": "ID",
        "code": "ID.RA-01",
        "name": "Risk Assessment",
        "description": "Asset vulnerabilities are identified and documented.",
        "guidance": "Regular vulnerability assessments help identify weaknesses before they can be exploited.",
        "version": "2.0",
        "is_active": True,
        "priority": "medium",
        "sort_order": 3,
    },
    {
        "family_code": "PR",
        "code": "PR.AC-01",
        "name": "Access Control - Identity Management",
        "description": "Identities and credentials are issued, managed, verified, revoked, and audited.",
        "guidance": "Strong identity management ensures that only authorized individuals have access to systems and data.",
        "version": "2.0",
        "is_active": True,
        "priority": "high",
        "sort_order": 1,
    },
    {
        "family_code": "PR",
        "code": "PR.AC-03",
        "name": "Access Control - Authentication",
        "description": "Users, devices, and other assets are authenticated.",
        "guidance": "Multi-factor authentication and strong authentication mechanisms reduce unauthorized access risks.",
        "version": "2.0",
        "is_active": True,
        "priority": "high",
        "sort_order": 2,
    },
    {
        "family_code": "PR",
        "code": "PR.DS-01",
        "name": "Data Security - At Rest",
        "description": "Data at rest is protected.",
        "guidance": "Encryption and access controls protect sensitive data when stored.",
        "version": "2.0",
        "is_active": True,
        "priority": "high",
        "sort_order": 3,
    },
    {
        "family_code": "DE",
        "code": "DE.CM-01",
        "name": "Continuous Monitoring",
        "description": "Networks and network services are monitored to find potentially adverse events.",
        "guidance": "Continuous monitoring helps detect anomalous activity and potential security incidents.",
        "version": "2.0",
        "is_active": True,
        "priority": "high",
        "sort_order": 1,
    },
    {
        "family_code": "DE",
        "code": "DE.AE-02",
        "name": "Adverse Events Analysis",
        "description": "Potentially adverse events are analyzed to better understand associated activities.",
        "guidance": "Analyzing events helps determine if they represent security incidents requiring response.",
        "version": "2.0",
        "is_active": True,
        "priority": "medium",
        "sort_order": 2,
    },
    {
        "family_code": "RS",
        "code": "RS.RP-01",
        "name": "Response Planning",
        "description": "Response plan is executed during or after an incident.",
        "guidance": "A well-documented and tested response plan ensures effective incident handling.",
        "version": "2.0",
        "is_active": True,
        "priority": "high",
        "sort_order": 1,
    },
    {
        "family_code": "RS",
        "code": "RS.CO-01",
        "name": "Response Communications",
        "description": "Personnel are aware of their roles and order of operations when a response is needed.",
        "guidance": "Clear communication ensures coordinated and effective incident response.",
        "version": "2.0",
        "is_active": True,
        "priority": "high",
        "sort_order": 2,
    },
    {
        "family_code": "RC",
        "code": "RC.RP-01",
        "name": "Recovery Planning",
        "description": "Recovery plan is executed during or after a cybersecurity incident.",
        "guidance": "Recovery plans help restore normal operations quickly and minimize impact.",
        "version": "2.0",
        "is_active": True,
        "priority": "high",
        "sort_order": 1,
    },
    {
        "family_code": "RC",
        "code": "RC.CO-01",
        "name": "Recovery Communications",
        "description": "Public relations are managed during recovery from an incident.",
        "guidance": "Effective communication maintains stakeholder trust during recovery.",
        "version": "2.0",
        "is_active": True,
        "priority": "medium",
        "sort_order": 2,
    },
]

NIST_IMPLEMENTATION_TIERS = [
    {
        "tier_level": 1,
        "name": "Partial",
        "description": "Risk management practices are not formalized, and risk is managed in an ad hoc and sometimes reactive manner.",
        "characteristics": "Limited awareness of cybersecurity risk at the organizational level; organization implements cybersecurity risk management on an irregular, case-by-case basis.",
        "framework": "NIST_CSF",
        "version": "2.0",
        "is_active": True,
    },
    {
        "tier_level": 2,
        "name": "Risk Informed",
        "description": "Risk management practices are approved by management but may not be established as organizational-wide policy.",
        "characteristics": "Risk-informed, but organization-wide approach to managing cybersecurity risk has not been established; organization is aware of cybersecurity risks but organization-wide approach is not consistently implemented.",
        "framework": "NIST_CSF",
        "version": "2.0",
        "is_active": True,
    },
    {
        "tier_level": 3,
        "name": "Repeatable",
        "description": "The organization's risk management practices are formally approved and expressed as policy.",
        "characteristics": "Organization-wide approach to managing cybersecurity risk that uses risk-informed policies, processes, and procedures to address potential cybersecurity events.",
        "framework": "NIST_CSF",
        "version": "2.0",
        "is_active": True,
    },
    {
        "tier_level": 4,
        "name": "Adaptive",
        "description": "The organization adapts its cybersecurity practices based on previous and current cybersecurity activities.",
        "characteristics": "Organization adapts to a changing cybersecurity landscape and responds to evolving and sophisticated threats in a timely manner based on lessons learned and predictive indicators.",
        "framework": "NIST_CSF",
        "version": "2.0",
        "is_active": True,
    },
]

SAMPLE_QUESTIONS = [
    {
        "control_code": "GV.OC-01",
        "question_text": "Has your organization documented its mission statement and how it relates to cybersecurity objectives?",
        "question_type": "YES_NO",
        "help_text": "Consider whether formal documentation exists that ties organizational mission to cybersecurity goals.",
        "is_required": True,
        "version": "1.0",
        "is_active": True,
        "sort_order": 1,
    },
    {
        "control_code": "GV.RM-01",
        "question_text": "Does your organization have a formal cybersecurity risk management strategy?",
        "question_type": "YES_NO",
        "help_text": "A formal strategy should be documented, approved by leadership, and regularly reviewed.",
        "is_required": True,
        "version": "1.0",
        "is_active": True,
        "sort_order": 1,
    },
    {
        "control_code": "ID.AM-01",
        "question_text": "What percentage of physical devices in your organization are inventoried?",
        "question_type": "MULTIPLE_CHOICE",
        "help_text": "Consider all devices including computers, servers, network equipment, and IoT devices.",
        "is_required": True,
        "version": "1.0",
        "is_active": True,
        "sort_order": 1,
        "options": [
            {"option_text": "0-25%", "option_value": "0-25", "score": 1.0, "sort_order": 1},
            {"option_text": "26-50%", "option_value": "26-50", "score": 2.0, "sort_order": 2},
            {"option_text": "51-75%", "option_value": "51-75", "score": 3.0, "sort_order": 3},
            {"option_text": "76-100%", "option_value": "76-100", "score": 4.0, "sort_order": 4},
        ],
    },
    {
        "control_code": "PR.AC-01",
        "question_text": "How does your organization manage user identities and access credentials?",
        "question_type": "TEXT",
        "help_text": "Describe your identity management processes, including provisioning, deprovisioning, and access reviews.",
        "is_required": True,
        "version": "1.0",
        "is_active": True,
        "sort_order": 1,
    },
    {
        "control_code": "PR.AC-03",
        "question_text": "Rate the maturity of your authentication mechanisms.",
        "question_type": "RATING",
        "help_text": "Consider factors like multi-factor authentication, password policies, and biometric authentication.",
        "is_required": True,
        "version": "1.0",
        "is_active": True,
        "sort_order": 1,
        "options": [
            {"option_text": "1 - Basic passwords only", "option_value": "1", "score": 1.0, "sort_order": 1},
            {"option_text": "2 - Password policies enforced", "option_value": "2", "score": 2.0, "sort_order": 2},
            {"option_text": "3 - MFA for some systems", "option_value": "3", "score": 3.0, "sort_order": 3},
            {"option_text": "4 - MFA for most systems", "option_value": "4", "score": 4.0, "sort_order": 4},
            {"option_text": "5 - MFA everywhere with risk-based authentication", "option_value": "5", "score": 5.0, "sort_order": 5},
        ],
    },
    {
        "control_code": "DE.CM-01",
        "question_text": "Does your organization have continuous monitoring capabilities for network traffic?",
        "question_type": "YES_NO",
        "help_text": "Continuous monitoring includes tools like SIEM, IDS/IPS, or network traffic analysis.",
        "is_required": True,
        "version": "1.0",
        "is_active": True,
        "sort_order": 1,
    },
    {
        "control_code": "RS.RP-01",
        "question_text": "Upload your incident response plan (if available).",
        "question_type": "FILE_UPLOAD",
        "help_text": "Accepted formats: PDF, DOCX, TXT. Maximum file size: 10MB.",
        "is_required": False,
        "version": "1.0",
        "is_active": True,
        "sort_order": 1,
    },
]
